version: '2'
services:
  mydata:
    build: ./docker/busybox
    image: busybox
    #container_name: mydata
    volumes:
    - .:/app:rw
  nodejs:
    build: ./docker/nodejs
    image: nodejs
    privileged: true
    volumes_from:
      - mydata
    ports:
      - "8080:8080"
  mongodb:
    build: ./docker/mongodb
    image: mymongo
    privileged: true
    command: --smallfiles
    volumes:
      - /mnt/sda1:/data/db:rw
    ports:
      - 27017:27017